### ISSUE TITLE
Not loading...

### ISSUE THREAD

**Issue by ruriescaper** [KirixenYT/Gogoanime#1]
Hey there, I used your script it works okay when it's comes to **search** or **view anime** but when I select options like **movies**, **genres**, etc. it doesn't show anything. 

Why is that? Can you **resolve** it?

**Comment by KirixenYT** [comment]
Actually I got this code off someone and I believe the key for the api isn't working anymore, as well as that I'm not that familiar with PHP too. Hope you can understand!

**Comment by KirixenYT** [comment]
I've fixed the issues now! tho sum of the contents might be buggy...

**Comment by ruriescaper** [comment]
> I've fixed the issues now! tho sum of the contents might be buggy...

Tnx, dude.

**Comment by ruriescaper** [comment]
There's another problem now, now the **search bar & home page** are not showing anything 😅

**Comment by KirixenYT** [comment]
There's nothing i can do for that since the gogoanime ajax domain have expired, all left now is to wait! 😔

**Comment by KirixenYT** [comment]
I've fixed the website and added some more of the web pages!

**Comment by ruriescaper** [comment]
> I've fixed the website and added some more of the web pages!

Hey dude, you done great work 👍, i appreciate it.

**Comment by ruriescaper** [comment]
Which free hosting are you using bro ?

**Comment by KirixenYT** [comment]
> Which free hosting are you using bro ?

Infinity

**Comment by KirixenYT** [comment]
> > I've fixed the website and added some more of the web pages!
> 
> Hey dude, you done great work 👍, i appreciate it.

Thanks man
