### ISSUE TITLE
Hey, new one

### ISSUE THREAD

**Issue by ruriescaper** [KirixenYT/Gogoanime#2]
Hey dude you changed something on your site: 
[gogoanimez.free.nf](http://gogoanimez.free.nf).
I'm curious if you used some kind of template of gogoanime.

**Comment by KirixenYT** [comment]
> Hey dude you changed something on your site: 
> [gogoanimez.free.nf](http://gogoanimez.free.nf).
> I'm curious if you used some kind of template of gogoanime. 

I simply went onto the real website and did inspect and took the ideas.

**Comment by ruriescaper** [comment]
That's awesome, I'm happy if I see this repository updated as well.
&
 I found another gogoanime-clone repository on GitHub [here](https://github.com/SonGorLick/gogoanime-clone).
Almost 2 years old script..

**Comment by KirixenYT** [comment]
> That's awesome, I'm happy if I see this repository updated as well.
> &
>  I found another gogoanime-clone repository on GitHub [here](https://github.com/SonGorLick/gogoanime-clone).
> Almost 2 years old script..

That is the same repository I took, just updated it to work!
