### ISSUE TITLE
Can I ask

### ISSUE THREAD

**Issue by XerAnime** [KirixenYT/Gogoanime#3]
Is this the right.. on info.php
<?php 
$base_url = "//{$_SERVER['SERVER_NAME']}";
$website_name = "Gogoanime";
$apiLink = ""; // https://gogoanimeapi-chi.vercel.app
if (date("d") > 15){
    $apiLink = ""; // https://gogoanimeapi-chi.vercel.app
}
?>

**Comment by KirixenYT** [comment]
> Is this the right.. on info.php
> 
> 15){ $apiLink = ""; // https://gogoanimeapi-chi.vercel.app } ?>

$apiLink = "https://gogoanimeapi-chi.vercel.app"; like this for both the var

**Comment by XerAnime** [comment]
Ok tnx..

**Comment by KirixenYT** [comment]
> Ok tnx..

Np

**Comment by XerAnime** [comment]
Try to visite.. http://gogoanime.wuaze.com/

**Comment by XerAnime** [comment]
Tnx bro..😀

**Comment by XerAnime** [comment]
Bro why isn't showing footer on home.

**Comment by KirixenYT** [comment]
> Bro why isn't showing footer on home.

Check all the files properly on the website where u have pasted ur file/folders

**Comment by XerAnime** [comment]
Ok bro tnx again.. it's showing now

**Comment by KirixenYT** [comment]
> Ok bro tnx again.. it's showing now

Np, glad i could be helpful... If u need any help in the future, feel to open any issues or join my discord server (ig u want)
