### ISSUE TITLE
Disqus isn't showing 

### ISSUE THREAD

**Issue by XerAnime** [KirixenYT/Gogoanime#4]
Bro the comment section isn't showing

**Comment by KirixenYT** [comment]
> Bro the comment section isn't showing 

Ye I've been trying to fix that problem too

**Comment by XerAnime** [comment]
Ok I'll try to explore the problem bro tnx

**Comment by KirixenYT** [comment]
> Ok I'll try to explore the problem bro tnx

Sure go ahead, I'll try to find what's causing it and update it

**Comment by XerAnime** [comment]
Tnx bro

**Comment by KirixenYT** [comment]
> Tnx bro

Np but u might have to wait until my laptop is fixed

**Comment by XerAnime** [comment]
Bro can I use gogoanime API...or the API that you provide?

**Comment by KirixenYT** [comment]
> Bro can I use gogoanime API...or the API that you provide?

The gogoanime-api is a little bit different from the api I provided, I've modified sum stuff so if u want to use original gogoanime-api u might have to change it on the website with the api correct link and response

**Comment by XerAnime** [comment]
Ok tnx bro...by the way Which file I to edit the disqus

**Comment by KirixenYT** [comment]
> Ok tnx bro...by the way Which file I need to edit the disqus

If I'm not mistaken, it's the streaming.php and animedetails.php

**Comment by XerAnime** [comment]
Ok thanks again bro

**Comment by KirixenYT** [comment]
> Ok thanks again bro

No problem
