### ISSUE TITLE
Your website gogoanime.free.nf is not loading 

### ISSUE THREAD

**Issue by aypedro** [KirixenYT/Gogoanime#5]
Please update the code 🙏🏽

**Comment by KirixenYT** [comment]
> Please update the code 🙏🏽

The website is working perfectly fine, http://gogoanimez.free.nf/home

**Comment by aypedro** [comment]
Please upload the files of your website that includes the home.php files

**Comment by KirixenYT** [comment]
> Please upload the files of your website that includes the home.php files 

Wdym...?

**Comment by aypedro** [comment]
I mean you should upload the same files of your website with the home directory

**Comment by KirixenYT** [comment]
> I mean you should upload the same files of your website with the home directory

Sure soon

**Comment by aypedro** [comment]
Please do 🙏🏽
