### ISSUE TITLE
My website is showing error 404 when I clicked on movies or try to search 

### ISSUE THREAD

**Issue by aypedro** [KirixenYT/Gogoanime#7]
Check it out https://gogoanime.freewebhostmost.com/anime-movies and tell me how to solve this

**Comment by KirixenYT** [comment]
> Check it out https://gogoanime.freewebhostmost.com/anime-movies and tell me how to solve this

Make sure ur files are there on the website hosting that you are using..

**Comment by aypedro** [comment]
I uploaded all the files but I still get the errors, what php version and extension do I need to install on my cpanel

**Comment by KirixenYT** [comment]
> I uploaded all the files but I still get the errors, what php version and extension do I need to install on my cpanel

Honestly you don't have to install anything, try enabling the .htaccess or rechecking the files
